server:
  port: 8080

spring:
  application:
    name: habilisadi_gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      server:
        webflux:
          routes:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVER_URL:localhost}:8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost}:${EUREKA_PORT:8080}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: "habilisadi_gateway"